### PR TITLE
CMS: Get testcase names from generator

### PR DESCRIPTION
**Pull request by SvizelPritula**
The CMS module currently searches through the `data/generated/` directory to find all the testcases, but that directory might not exist for some generators. With this change, the CMS module will reuse the list generated by the pipeline.

### CODE REVIEW

**Review by 5K1PY — CHANGES_REQUESTED** [review]
It might be actually nicer to return `TaskPath` objects from the pipeline if you will convert it back anyway.

**Comment by 5K1PY** [comment]
But with `TaskPath`s, we also give the full path to the input. This removes the need to guess the folder, to which the input belongs. If we needed to change the name of the inputs folder with current interface, we would break the things that use it.

Overall `TaskPath`s are more resilient to change.

**Comment by SvizelPritula** [comment]
> This removes the need to guess the folder

Doesn't `TaskPath.input_path` handle that? We need to rely on `TaskPath.output_file` anyway.

**Review by 5K1PY — APPROVED** [review]
Thanks!

> Doesn't TaskPath.input_path handle that? We need to rely on TaskPath.output_file anyway.

There is a certain story about `cms-old` generators having `tests/` hardcoded instead of the first argument...

**Pull request merged**
