### PR TITLE
Verdict messages

### LINKED ISSUE #223: Show judge verdicts in `verbosity=2`
Not just kind of verdict

### PR DESCRIPTION
**Pull request by 5K1PY**
Fixes #223

### CODE REVIEW

**Comment by SvizelPritula** [comment]
This doesn't actually implement #223, since the message isn't show anywhere.

**Comment by 5K1PY** [comment]
> This doesn't actually implement #223, since the message isn't show anywhere.

When I run it on `sum_cms`:
```
...
  Subtask B: 1p/2p                                                                     slowest 0.00s
    02_01.in (1p): |OK|                                                                        0.00s
    02_02.in (2p): OK                                                                          0.00s
    02_03.in (1p): |OK|                                                                        0.00s
    02_04.in (1p): |OK|                                                                        0.00s
    02_05.in (1p): |OK|                                                                        0.00s
...
```

**Comment by SvizelPritula** [comment]
> > This doesn't actually implement #223, since the message isn't show anywhere.
> 
> When I run it on `sum_cms`:

Ah, it seems I missed the relevant change.

**Review by SvizelPritula — APPROVED** [review]
LGTM

**Pull request merged**
